### ISSUE TITLE
REAPER text file reading is very primitive

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-matrices#3]
I have done some experiments with reading matrices into REAPER today. It turns out that REAPER functionalities for this are fairly primitive. REAPER basically needs each line to contain one number only. Here's from the [documentation](http://reaper.fm/sdk/js/file.php#js_file) of file I/O:

> The format of each line in the text file can be either a floating point number, a binary number beginning with 'b', i.e. b0101010111, or a hexadecimal number beginning with 'x', i.e. xDEADF000. 

This implies that the current formatting of matrices can not be used with Reaper.

The only suggestion that I can think of if we want to have a shared library of matrices, is that they have to be organised according to the rather cumbersome convention:

```
<number of rows>
<number of columns>

<value of cell 1, 1>
<value of cell 1, 2>
....
<value of cell 1, n>

<value of cell 2, 1>
<value of cell 2, 2>
....
<value of cell 2, n>

....

<value of cell m, 1>
<value of cell m, 2>
....
<value of cell m, n>
```

Any thoughts, @joslloand ?

**Comment by joslloand** [comment]
**Grrr!**

**Comment by joslloand** [comment]
Actually... it may not be such a show stopper, but it does suggest some added complexity. The use of matrices [Matrix loading/writing #4](https://github.com/ambisonictoolkit/atk-sc3/issues/4) offers a number of advantages:
- synchronization of matrices across platforms
- _easy_ expansion of matrix encoders & decoders
- integration with 3rd party (encoders &) decoders, e.g., [ADT](https://bitbucket.org/ambidecodertoolbox/adt.git), Politis' [HOA Library](https://github.com/polarch/Higher-Order-Ambisonics)

The last of these offers substantial gains, in that we'd have easy access to methods for irregular designs. @mtmccrea has been making progress with the [`matrix-loading`](https://github.com/ambisonictoolkit/atk-sc3/tree/matrix-loading) branch of [atk-sc3](https://github.com/ambisonictoolkit/atk-sc3).

Currently implemented are two matrix loading / writing forms:
- .yaml: includes meta data
- .txt: matrix only

The last of these is what we were expecting would allow easy 3rd party integration. As it appears Reaper won't easily be able to support the .txt form, we could consider:
- .yaml: includes meta data
- .txt: matrix only
- .mosl: matrix only, on single lines

The .mosl (matrix-only-single-lines, we could come up with another name) form wouldn't easily solve 3rd party integration, unless the 3rd party tools have this output option. In the short term, though, ATK 'built-ins' _could_ be supplied this way....

**Comment by lossius** [comment]
It should be fairly straight-forward to provide a Ruby script or similar that can generate the .mosl file from .yaml or .txt (matrix only).

Apart from that I would suggest that we use .mosl.txt or something similar as file ending, so that it remains clear that it is a text format file.

**Comment by mtmccrea** [comment]
I think at this point Jo would be exporting matrices manually from python. Because this is yet to be done, I think adding that format to the export process from python would be pretty straightforward, unless there is another use for a separate script to generate the .mosl files.

We'll want to decide if we will support reading/writing .mosl in atk-sc, which would be straightforward.  That would allow users to author their own matrices in SC (or elsewhere, for that matter) for use in Reaper. In that case, atk-reaper would also be looking in the "ATK/extensions/matrices" folders for available matrices. (That folder structure hasn't yet been finalized).  

If on the other hand they're "stuck" with what we provide (in the ATK/matrices folders), then we wouldn't bother reading/writing the format in SC.

**Comment by lossius** [comment]
I have done some further testing in Reaper:

_File ending needs to be .txt_

I've tried working with matrix files with .mosl file ending, and Reaper is unable to read them. So we'll have to use *.mosl.txt. This I have confirmed that works fine.

_Text files can have comments and empty lines_

It turns out that it is possible to add comment lines starting with `//`. It is also possible to have empty lines. Additionally anything beyond the first value of a line will be ignored, so we can have inline comments as well. I believe this greatly helps on readability, as illustrated here:

```
// Dimensions
4
4

// Row 1
1.002   
2.002
3.002
4.002

// Row 2
5.002
6.002
7.002
8.002

// Row 3
9.002         // Cell 3 1
10.002        // Cell 3 2
11.002        // Cell 3 3
12.002        // Cell 3 4

// Row 4
13.002
14.002
15.002
16.002
```

IMHO the inline comments might be a bit over the top, but empty lines and demarcations of each rows I find useful. I'll just go ahead and make mosl.txt files for the AmbiX-related matrices, so that I can add encoders and decoders from and to AmbiX, addressing https://github.com/ambisonictoolkit/atk-reaper/issues/10.

And if this format makes sense, I suppose we can close this issue, and replace it by an issue to add python code for exporting to mosl.txt.

**Comment by joslloand** [comment]
This solution sounds like I'll work.

Does everyone like the `.mosl` designation?

For generating matrices, it won't be difficult to update the python code to throw out this form, too. (I still need to add the `.yaml` version too.)

**Comment by mtmccrea** [comment]
`.mosl` seems find to me.

**Comment by joslloand** [comment]
atk-reaper v1.0.0.b9 now includes .mosl.txt matrices

https://github.com/ambisonictoolkit/atk-reaper/releases/tag/v1.0.0.b9
